/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.*;
/**
 *
 * @author AMEYA A
 */
public class MainSelectionPage extends javax.swing.JFrame {

    /**
     * Creates new form MainSelectionPage
     */
    ConfigureSystem cSysMain;
    public MainSelectionPage(ConfigureSystem cSysMain) {
        initComponents();
        this.cSysMain = cSysMain;
    }
    public MainSelectionPage() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPatientLogin = new javax.swing.JButton();
        btnSysAdminLogin = new javax.swing.JButton();
        btnHosAdminLogin = new javax.swing.JButton();
        btnDoctorLogin = new javax.swing.JButton();
        btnComAdminLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPatientLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnPatientLogin.setText("Patient Login");
        btnPatientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLoginActionPerformed(evt);
            }
        });

        btnSysAdminLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnSysAdminLogin.setText("System Admin Login");
        btnSysAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysAdminLoginActionPerformed(evt);
            }
        });

        btnHosAdminLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnHosAdminLogin.setText("Hospital Admin Login");
        btnHosAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHosAdminLoginActionPerformed(evt);
            }
        });

        btnDoctorLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnDoctorLogin.setText("Doctors Login");
        btnDoctorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorLoginActionPerformed(evt);
            }
        });

        btnComAdminLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnComAdminLogin.setText("Community Admin Login");
        btnComAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnPatientLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(btnSysAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(btnHosAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(btnComAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnDoctorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSysAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHosAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnDoctorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLoginActionPerformed
        // TODO add your handling code here:
        new PatientLogin(cSysMain).setVisible(true);
        this.setVisible(false);
        //        splitPane.setRightComponent(dash);
        //        new DashBoardJFrame().setVisible(true);
        //        this.setVisible(false);
    }//GEN-LAST:event_btnPatientLoginActionPerformed

    private void btnSysAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysAdminLoginActionPerformed
        // TODO add your handling code here:
        new SystemAdminLogin(cSysMain).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSysAdminLoginActionPerformed

    private void btnHosAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHosAdminLoginActionPerformed
        // TODO add your handling code here:
        new HospitalAdminLogin(cSysMain).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHosAdminLoginActionPerformed

    private void btnDoctorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorLoginActionPerformed
        // TODO add your handling code here:
        new DoctorLogin(cSysMain).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDoctorLoginActionPerformed

    private void btnComAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComAdminLoginActionPerformed
        // TODO add your handling code here:
        new CommunityAdminLogin(cSysMain).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnComAdminLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSelectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComAdminLogin;
    private javax.swing.JButton btnDoctorLogin;
    private javax.swing.JButton btnHosAdminLogin;
    private javax.swing.JButton btnPatientLogin;
    private javax.swing.JButton btnSysAdminLogin;
    // End of variables declaration//GEN-END:variables
}
